### ISSUE TITLE
Any way to make esx_menu_default menu to use not NativeUI because its taking to much ms like 0.16 when is menu opened!

### ISSUE THREAD

**Issue by Tinky124** [andristum/dpemotes#1]
I think you need to make so its using like default esx_animations like menu default because its taking to much ms like idle script taking 0.02ms but when in menu its taking like 0.16ms 0.18ms its too much!

**Comment by dhawton** [comment]
That is pretty typical of using NativeUI across any script and is not that bad.. especially when you look at ESX Menu's load when it is open. Ideally the author should avoid ESX menus to keep the script free of specific framework requirements.

**Comment by andristum** [comment]
I like to keep my resources standalone, and i currently have no plans to port the emotemenu to another menu framework thingie
